version: "2.2"

services:
  pet-clinic:
    image: pet-clinic:latest
    # prometheus is still not visible (fixes db services visibility)
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - prometheus
#      - postgres
#    environment:
#      SPRING_PROFILES_ACTIVE: postgres
  mysql:
    image: mysql:8.2
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    profiles:
      - mysql
  postgres:
    image: postgres:16.1
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    profiles:
      - postgres
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
