version: "2.2"

services:
  pet-clinic:
    image: pet-clinic:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9999:9999"
# FIXME: sucks for some reason - db port is not exposed (probably define network explicitly)
    depends_on:
      - prometheus
#      - postgres
#    environment:
#      SPRING_PROFILES_ACTIVE: postgres
  mysql:
    image: mysql:8.2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    profiles:
      - mysql
  postgres:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    profiles:
      - postgres
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
