database=sqlite
spring.datasource.url=jdbc:sqlite:src/main/resources/db/sqlite/petclinic.sqlite3
spring.datasource.username=${SQLITE_USER:petclinic}
spring.datasource.password=${SQLITE_PASS:petclinic}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=embedded
spring.jpa.show-sql=true
